In [51]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
customers = pd.read_excel("Zepto_Dataset.xlsx",sheet_name="Customers")
products = pd.read_excel("Zepto_Dataset.xlsx",sheet_name="Products")
orders = pd.read_excel("Zepto_Dataset.xlsx",sheet_name="Orders")
transactions = pd.read_excel("Zepto_Dataset.xlsx",sheet_name="Transactions")
ratings = pd.read_excel("Zepto_Dataset.xlsx",sheet_name="Ratings")
delivery = pd.read_excel("Zepto_Dataset.xlsx",sheet_name="Delivery")

In [53]:
file=[customers,products,orders,transactions,ratings,delivery]

In [54]:
for i in file :
  i.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   C_ID          15000 non-null  object
 1   CName         15000 non-null  object
 2   email         15000 non-null  object
 3   gender        15000 non-null  object
 4   Age           15000 non-null  int64
 5   City          15000 non-null  object
 6   State         15000 non-null  object
 7   Address       15000 non-null  object
 8   created_date  15000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 1.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   P_ID      15000 non-null  object
 1   PName     15000 non-null  object
 2   Category  15000 non-null  object
 3   Brand     15000 non-null  object
 4   Price     15000 non-null  float64
dtypes: float64(1), object(4)
memory usage: 586.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Or_ID            15000 non-null  object
 1   C_ID             15000 non-null  object
 2   P_ID             15000 non-null  object
 3   Order_Date       15000 non-null  datetime64[ns]
 4   Order_Time       15000 non-null  object
 5   Qty              15000 non-null  int64
 6   Coupon           15000 non-null  object
 7   Coupon_Discount  15000 non-null  int64
 8   DP_ID            15000 non-null  object
dtypes: datetime64[ns](1), int64(2), object(6)
memory usage: 1.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Tr_ID               15000 non-null  object
 1   Or_ID               15000 non-null  object
 2   Transaction_Mode    15000 non-null  object
 3   Transaction_Status  15000 non-null  object
dtypes: object(4)
memory usage: 468.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   RT_ID                    15000 non-null  object
 1   Or_ID                    15000 non-null  object
 2   Prod_Rating              10000 non-null  float64
 3   Delivery/Service_Rating  10000 non-null  float64
dtypes: float64(2), object(2)
memory usage: 468.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DP_ID             15000 non-null  object
 1   DP_name           15000 non-null  object
 2   Delivery Partner  15000 non-null  object
 3   Unnamed: 3        0 non-null      float64
 4   Unnamed: 4        0 non-null      float64
 5   Unnamed: 5        0 non-null      float64
 6   Unnamed: 6        999 non-null    object
dtypes: float64(3), object(4)
memory usage: 820.4+ KB

In [55]:
for i in file:
  print("null values : \n",i.isnull().sum())
  print("duplicated values : ",i.duplicated().sum())

null values :
 C_ID            0
CName           0
email           0
gender          0
Age             0
City            0
State           0
Address         0
created_date    0
dtype: int64
duplicated values :  0
null values :
 P_ID        0
PName       0
Category    0
Brand       0
Price       0
dtype: int64
duplicated values :  0
null values :
 Or_ID              0
C_ID               0
P_ID               0
Order_Date         0
Order_Time         0
Qty                0
Coupon             0
Coupon_Discount    0
DP_ID              0
dtype: int64
duplicated values :  0
null values :
 Tr_ID                 0
Or_ID                 0
Transaction_Mode      0
Transaction_Status    0
dtype: int64
duplicated values :  0
null values :
 RT_ID                         0
Or_ID                         0
Prod_Rating                5000
Delivery/Service_Rating    5000
dtype: int64
duplicated values :  164
null values :
 DP_ID                   0
DP_name                 0
Delivery Partner        0
Unnamed: 3          15000
Unnamed: 4          15000
Unnamed: 5          15000
Unnamed: 6          14001
dtype: int64
duplicated values :  0

In [56]:
customers.head(3)

,C_ID,CName,email,gender,Age,City,State,Address,created_date
0,CS_11000001,Anay Singhal,Anay_Singhal@gmail.com,Female,62,Hyderabad,Telangana,"20/923\nNarayan Chowk, Chittoor 694343",2025-03-03
1,CS_11000002,Falguni Korpal,Falguni_Korpal@gmail.com,Male,64,Jamshedpur,Jharkhand,"587, Saini Road, Ajmer 319147",2023-05-14
2,CS_11000003,Sachi Sheth,Sachi_Sheth@gmail.com,Female,57,Varanasi,Uttar Pradesh,"78/281\nMishra Street, Vasai-Virar 996221",2025-01-07

In [57]:
customers.drop(
    columns=['email','Address'],
    inplace=True
)

In [58]:
customers.head(1)

          C_ID         CName  gender  Age       City      State created_date
0  CS_11000001  Anay Singhal  Female   62  Hyderabad  Telangana   2025-03-03

In [59]:
products.head(2)

          P_ID          PName       Category      Brand   Price
0  PD_21000001  Tempore Juice  Personal Care  Haldirams  413.50
1  PD_21000002     At Shampoo      Home Care  Haldirams  637.32

In [60]:
orders.head(2)

,Or_ID,C_ID,P_ID,Order_Date,Order_Time,Qty,Coupon,Coupon_Discount,DP_ID
0,OR_31000001,CS_11005317,PD_21001301,2025-02-06,13:44:42,3,WELCOME10,15,DV_61000087
1,OR_31000002,CS_11000423,PD_21003593,2024-03-06,21:32:50,10,RALLY20,10,DV_61000085

In [61]:
orders.drop(
    columns=['Coupon'],
    inplace=True
)

In [62]:
orders.head(1)

,Or_ID,C_ID,P_ID,Order_Date,Order_Time,Qty,Coupon_Discount,DP_ID
0,OR_31000001,CS_11005317,PD_21001301,2025-02-06,13:44:42,3,15,DV_61000087

In [63]:
transactions.head(2)

         Tr_ID        Or_ID Transaction_Mode Transaction_Status
0  TR_41000001  OR_31002037              COD             Failed
1  TR_41000002  OR_31008376       Debit Card             Failed

In [64]:
ratings.head(2)

          RT_ID        Or_ID  Prod_Rating  Delivery/Service_Rating
0  RT_101000001  OR_31009479          4.0                      5.0
1  RT_101000002  OR_31001385          2.0                      2.0

In [65]:
delivery.head()

,DP_ID,DP_name,Delivery Partner,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,DV_61000001,Omaja Dhawan,Delhivery,NaN,NaN,NaN,NaN
1,DV_61000002,Chanakya Bail,Xpressbees,NaN,NaN,NaN,
2,DV_61000003,Bina Borde,Delhivery,NaN,NaN,NaN,
3,DV_61000004,Nimrat Butala,Xpressbees,NaN,NaN,NaN,
4,DV_61000005,Ekbal Sathe,Xpressbees,NaN,NaN,NaN,

In [66]:
delivery.drop(
    columns=['Unnamed: 3','Unnamed: 4','Unnamed: 5','Unnamed: 6'],
    inplace=True
)

In [67]:
delivery.head(1)

         DP_ID       DP_name Delivery Partner
0  DV_61000001  Omaja Dhawan        Delhivery

In [68]:
for df in file:
    print(df.isnull().sum())

C_ID            0
CName           0
gender          0
Age             0
City            0
State           0
created_date    0
dtype: int64
P_ID        0
PName       0
Category    0
Brand       0
Price       0
dtype: int64
Or_ID              0
C_ID               0
P_ID               0
Order_Date         0
Order_Time         0
Qty                0
Coupon_Discount    0
DP_ID              0
dtype: int64
Tr_ID                 0
Or_ID                 0
Transaction_Mode      0
Transaction_Status    0
dtype: int64
RT_ID                         0
Or_ID                         0
Prod_Rating                5000
Delivery/Service_Rating    5000
dtype: int64
DP_ID               0
DP_name             0
Delivery Partner    0
dtype: int64

In [69]:
ratings.shape

(15000, 4)

In [70]:
ratings[
    ratings['Prod_Rating'].isna() &
    ratings['Delivery/Service_Rating'].isna()
].shape

(5000, 4)

In [71]:
# Remove duplicates
ratings.drop_duplicates(inplace=True)

# Check data types
ratings.info()

# Verify rating range
ratings['Prod_Rating'].describe()
ratings['Delivery/Service_Rating'].describe()

<class 'pandas.core.frame.DataFrame'>
Index: 14836 entries, 0 to 14999
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   RT_ID                    14836 non-null  object
 1   Or_ID                    14836 non-null  object
 2   Prod_Rating              10000 non-null  float64
 3   Delivery/Service_Rating  10000 non-null  float64
dtypes: float64(2), object(2)
memory usage: 579.5+ KB

count    10000.000000
mean         3.026300
std          1.409612
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: Delivery/Service_Rating, dtype: float64

In [72]:
df = orders.merge(customers,on='C_ID')

In [73]:
df = df.merge(products,on='P_ID')

In [74]:
df = df.merge(transactions,on='Or_ID')

In [75]:
df = df.merge(ratings,on='Or_ID')

In [76]:
df['Revenue'] = df['Qty'] * df['Price']

In [77]:
df['Discount_Amount'] = (
    df['Revenue'] * df['Coupon_Discount']/100
)

In [78]:
df['Final_Revenue'] = (
    df['Revenue'] - df['Discount_Amount']
)

In [79]:
df['Final_Revenue'].sum()

np.float64(36222893.4425)

In [80]:
top_products = (
    df.groupby('PName')['Final_Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

In [81]:
df.groupby('Category')['Final_Revenue'].sum()

Category
Beverages        5.798617e+06
Dairy            6.067833e+06
Groceries        6.217697e+06
Home Care        6.723216e+06
Personal Care    5.343651e+06
Snacks           6.071879e+06
Name: Final_Revenue, dtype: float64

In [82]:
df.groupby('City')['Or_ID'].count()

City
Agra             212
Ahmedabad        137
Ajmer             96
Ambala           206
Amritsar         212
                ...
Vadodara         164
Varanasi         133
Vijayawada       235
Visakhapatnam    151
Warangal         144
Name: Or_ID, Length: 90, dtype: int64

In [83]:
df['Transaction_Mode'].value_counts()

Transaction_Mode
COD            3068
Credit Card    2991
Debit Card     2954
Wallet         2901
UPI            2838
Name: count, dtype: int64

In [84]:
df['Prod_Rating'].mean()

np.float64(3.007524403470716)

In [85]:
 df.to_excel("zepto_cleaned.xlsx", index=False)

In [86]:
from google.colab import files
files.download("zepto_cleaned.xlsx")

In [87]:
cleaned=pd.read_excel("zepto_cleaned.xlsx")

In [88]:
cleaned.head()

,Or_ID,C_ID,P_ID,Order_Date,Order_Time,Qty,Coupon_Discount,DP_ID,CName,gender,...,Price,Tr_ID,Transaction_Mode,Transaction_Status,RT_ID,Prod_Rating,Delivery/Service_Rating,Revenue,Discount_Amount,Final_Revenue
0,OR_31000001,CS_11005317,PD_21001301,2025-02-06,13:44:42,3,15,DV_61000087,Isha Boase,Female,...,142.25,TR_41004226,COD,Failed,RT_101006049,1,3,426.75,64.0125,362.7375
1,OR_31000001,CS_11005317,PD_21001301,2025-02-06,13:44:42,3,15,DV_61000087,Isha Boase,Female,...,142.25,TR_41010487,Debit Card,Failed,RT_101006049,1,3,426.75,64.0125,362.7375
2,OR_31000004,CS_11004079,PD_21007443,2024-05-20,07:08:34,9,10,DV_61000292,Raghav Prashad,Male,...,599.19,TR_41004874,UPI,Failed,RT_101002512,1,4,5392.71,539.2710,4853.4390
3,OR_31000004,CS_11004079,PD_21007443,2024-05-20,07:08:34,9,10,DV_61000292,Raghav Prashad,Male,...,599.19,TR_41004874,UPI,Failed,RT_101002805,5,2,5392.71,539.2710,4853.4390
4,OR_31000004,CS_11004079,PD_21007443,2024-05-20,07:08:34,9,10,DV_61000292,Raghav Prashad,Male,...,599.19,TR_41011135,COD,Success,RT_101002512,1,4,5392.71,539.2710,4853.4390

In [91]:
cleaned.shape

(14752, 27)

In [90]:
cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14752 entries, 0 to 14751
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Or_ID                    14752 non-null  object
 1   C_ID                     14752 non-null  object
 2   P_ID                     14752 non-null  object
 3   Order_Date               14752 non-null  datetime64[ns]
 4   Order_Time               14752 non-null  object
 5   Qty                      14752 non-null  int64
 6   Coupon_Discount          14752 non-null  int64
 7   DP_ID                    14752 non-null  object
 8   CName                    14752 non-null  object
 9   gender                   14752 non-null  object
 10  Age                      14752 non-null  int64
 11  City                     14752 non-null  object
 12  State                    14752 non-null  object
 13  created_date             14752 non-null  datetime64[ns]
 14  PName                    14752 non-null  object
 15  Category                 14752 non-null  object
 16  Brand                    14752 non-null  object
 17  Price                    14752 non-null  float64
 18  Tr_ID                    14752 non-null  object
 19  Transaction_Mode         14752 non-null  object
 20  Transaction_Status       14752 non-null  object
 21  RT_ID                    14752 non-null  object
 22  Prod_Rating              14752 non-null  int64
 23  Delivery/Service_Rating  14752 non-null  int64
 24  Revenue                  14752 non-null  float64
 25  Discount_Amount          14752 non-null  float64
 26  Final_Revenue            14752 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(5), object(16)
memory usage: 3.0+ MB